
import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { fetchStylesAndScriptsByUri } from '@/lib/utils';
import Styles from "@/components/Styles";
import Scripts from "@/components/Scripts";

import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const { stylesheets, scripts } = await fetchStylesAndScriptsByUri('/sample-page');
  return (
    <html lang="en">
      <head>
      <Styles stylesheets={stylesheets} />
      <Scripts scripts={scripts} type="header" />
      </head>
      <body className={inter.className}>
        {children}
        <Scripts scripts={scripts} type="footer" />
      </body>
    </html>
  );
}
