
import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Inter } from "next/font/google";

import { fetchStylesAndScriptsByUri } from '@/lib/utils';
import Styles from "@/components/Styles";
import Scripts from "@/components/Scripts";

import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const uri = headers().get('x-uri') || '/';
  console.log('uri', uri);
  const { stylesheets, scripts } = await fetchStylesAndScriptsByUri(uri);
  return (
    <html lang="en">
      <head>
        <Styles stylesheets={stylesheets} />
        <Scripts type="header" scripts={scripts} />
      </head>
      <body className={inter.className}>
        {children}
        <Scripts type="footer" scripts={scripts} />
      </body>
    </html>
  );
}
